### ISSUE TITLE
在手机上显示倒计时问题

### ISSUE THREAD

**Issue by zycn0910** [fanyy0418/areacode-page#1]
在手机上显示，时间倒计时乱码，变静态，电脑上显示倒计时乱码

**Comment by fanyy0418** [comment]
你是直接fork的仓库么？fork的话，不要格式化源代码，不然显示会和正版不太一样。动态显示时间使用的是switch case，用的JavaScript实现的，通过getElementById更改元素位置，正版是动态计算位置，我没弄那么复杂，你可以在静态页面，手动调试0-9的位置，确保自己的显示正常就可以了。电脑上乱码不用管，在手机上显示正常就行了。调试一定要在手机上调试，可以看B站鱼皮的视频，用natapp在本地搭一个服务器用来调试，调试好上线到github后用git pages来日常使用。

有任何问题可以继续跟我回复。

**Comment by zycn0910** [comment]
我直接git clone在手机上显示是这样的
![微信图片_20221002203720](https://user-images.githubusercontent.com/46790182/193454388-b9860b60-8405-4468-89b3-4dea29d70b08.jpg)

**Comment by fanyy0418** [comment]
> 我直接git clone在手机上显示是这样的 ![微信图片_20221002203720](https://user-images.githubusercontent.com/46790182/193454388-b9860b60-8405-4468-89b3-4dea29d70b08.jpg)


这个是正常的，你可以调节每个switch case中0-9的位置，然后调整到你的手机显示正常就行了。每个case后面跟的有一个移动值，你可以通过调节第一位数字的位置（比如 20:51:31 中，你可以调节2这个数字的位置，把这个位置的0-9都调的在你的手机显示正常后，把这个调好的px值复制到每一个对应的case后面就可以了），然后我看你的截图，动态时间应该是正常的吧？

**Comment by zycn0910** [comment]
我用vscode编辑，但是服务器用ftp，每次改完再上传，在刷新访问好麻烦，想问一下能不能直接扒他的网页

**Comment by fanyy0418** [comment]
> 我用vscode编辑，但是服务器用ftp，每次改完再上传，在刷新访问好麻烦，想问一下能不能直接扒他的网页

我也是用的vsc，也是扒的他的网页，复制下来的网页不会自动跳动时间
